const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST';
const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
const FETCH_COUNTRY_FAILURE = 'FETCH_COUNTRY_FAILURE';

export { FETCH_COUNTRY_REQUEST, FETCH_COUNTRY_SUCCESS, FETCH_COUNTRY_FAILURE };
